package com.hfnu.study.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createor
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Long createor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.comment_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Integer commentAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.view_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Integer viewAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.like_count
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.tags
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_create
     *
     * @return the value of question.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_create
     *
     * @param gmtCreate the value for question.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_modified
     *
     * @return the value of question.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_modified
     *
     * @param gmtModified the value for question.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createor
     *
     * @return the value of question.createor
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Long getCreateor() {
        return createor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createor
     *
     * @param createor the value for question.createor
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setCreateor(Long createor) {
        this.createor = createor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.comment_account
     *
     * @return the value of question.comment_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Integer getCommentAccount() {
        return commentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.comment_account
     *
     * @param commentAccount the value for question.comment_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setCommentAccount(Integer commentAccount) {
        this.commentAccount = commentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.view_account
     *
     * @return the value of question.view_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Integer getViewAccount() {
        return viewAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.view_account
     *
     * @param viewAccount the value for question.view_account
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setViewAccount(Integer viewAccount) {
        this.viewAccount = viewAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.like_count
     *
     * @return the value of question.like_count
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.like_count
     *
     * @param likeCount the value for question.like_count
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.tags
     *
     * @return the value of question.tags
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.tags
     *
     * @param tags the value for question.tags
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbg.generated Mon Mar 30 23:16:46 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}